### ISSUE TITLE
allow length > 1 id input in id converter fxns

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/citecorp#1]
For  oc_doi2ids, oc_pmid2ids, and oc_pmcid2ids

**Comment by Selbosh** [comment]
This is how I do it for now, as a wrapper around the original function. The `id` column keeps track of which row corresponds to which input.

```r
purrr::map_dfr(
  c('10.1093/biomet/79.3.531', '10.1093/biomet/80.3.527'),
  oc_doi2ids, .id = 'id'
)
```

or

```r
library(dplyr)
c('10.1093/biomet/79.3.531', '10.1093/biomet/80.3.527') %>%
  lapply(oc_doi2ids) %>%
  bind_rows(.id = 'id')
````

or in base R

```r
local({
  lst <- lapply(c('10.1093/biomet/79.3.531', '10.1093/biomet/80.3.527'), oc_doi2ids)
  df <- do.call(rbind, lst)
  df$id <- rep.int(seq_along(lst), lengths(lst))
  df
})
```

**Comment by sckott** [comment]
thanks @Selbosh - was just putting this off so i could get out the first version to cran sooner. pushing a change now

**Comment by sckott** [comment]
@Selbosh if you have time, if you could reinstall and try again, let me know what you think - output data.frame format has changed

**Comment by sckott** [comment]
thanks @amoeba for his Sparql based brain

**Comment by sckott** [comment]
right, i should have included in the tests more identifier egs, including the examples you gave.
