### ISSUE TITLE
Error in doi2ids - arguments imply differing number of rows: 0, 1

### ISSUE THREAD

**Issue by Selbosh** [ropenscilabs/citecorp#2]
I try to convert DOIs to IDs, without success. And I know for a fact that these DOIs are on the Open Citations Corpus, because that's where I found them!

## Minimal working example

```r
library(citecorp)
oc_doi2ids('10.1093/biomet/79.3.531')
oc_doi2ids('10.1093/biomet/80.3.527')
```

Error returned in each case:

```r
Error in data.frame(type = gsub("\\.type", "", names(tmp[, grep("\\.type",  : 
  arguments imply differing number of rows: 0, 1
```

## The problem

This is a common bug due to an unexpected behaviour in how subsetting data frames works. That is, if you subset a data frame and the result is one column, it is automatically collapsed to a vector (**not** a one-column data frame) unless you specify `drop = FALSE`.

Here is the culprit
https://github.com/ropenscilabs/citecorp/blob/32929e8a8504652c8f767343166dc1c7ee7f5537/R/oc_lookup.R#L9

And the bug is triggered whenever the preceding `tmp` variable contains exactly one column with the suffix `.type`, for example
```
  paper.type                           paper.value
1        uri https://w3id.org/oc/corpus/br/5902173
```
because if you run the above code on this, you get `character(0)` as a result, which is not what you want.

## Solution

Whilst I could add `, drop = FALSE` I would take the opportunity to simplify the code instead. The following works on the examples above.

```r
    tmp <- data.frame(
      type  = gsub('\\.type', '', grep('\\.type', names(tmp), value = TRUE)),
      value = as.vector(tmp[, grep('\\.value', names(tmp))]),
      stringsAsFactors = FALSE
    )
```

**Comment by sckott** [comment]
thanks for this. i confirm getting the same thing. looking at the PR
